//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace pp.БД
{
    using System;
    using System.Collections.Generic;
    
    public partial class Subjects
    {
        public int idSubject { get; set; }
        public string nameSubject { get; set; }
        public string description { get; set; }
    }
}
